before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
after_success:
- "/bin/bash ./send_to_discord success $DISCORD_BUILD_STATUS_WEBHOOK_URL"
after_failure:
- "/bin/bash ./send_to_discord failure $DISCORD_BUILD_STATUS_WEBHOOK_URL"
notifications:
  email: false
language: bash
services:
- docker
jobs:
  include:
  - stage: build
    script:
    - make build
    - make deploy_commit
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy_latest
  on:
    branch: master
env:
  global:
    # discord webhook
  - secure: ntCT4nUGGpXpgoF564SXud1SPJUfQD9EB7lU+niGvkl4MDHnqyEq0ygQqBO6xK00vVUzyzi1Yc1TzR4b6KX/8ubnOSH67Jxz5f2VZgq4IaXnO3VJRBGzdqeycuqRLv7oc7UmwospU+FJfElYfa2IpNs4atH4Jn/9ZgvZW6SyeKQngct64DTQHo3IWxXIsMzTEr7cr5AOeeBx8CuDLKzGvBOK2Q01sZQw5xCWjr0Pq3rX43JrOdRpSiJRtGIAjdu/U28gFbuoPaH3goqrxEfn5qGDkxUbkSZtgo21g+5wNaPcND2wvfYk2GBqsQhLteJi3JW2YZGyAEw8BDvPEBQkllgvE9B9NLAKtmIe2huzTywXJOcyUBG3NseBBeCXoliy9rWZQ4tNj/aCihXEDhIAf5J+dD/bV40l5XHdU8LiBzTjoOG9n8XAeFdRmjEECHpcBfJ+gfS1lXmxC6uFnfSnnnL3at3yHkTK268zbQ1sFfRVY8seABo5ZUG2s2OKL48w8e9Gilwe3EntOrTgim4EuKO7RGO2/rPjNXvO6OPd9Nvg+qsdDoBHs2XNd6cGy2fvriqBujwEJlIZN31PajYv6LYhiuWn9qreyZ4EguRrd88QMwrPVQICDC3Tx7Xu/j0e3zl1FK8Rt2ZFgsfiiYZ2NMHA031QzGUmCbVh4fmNWcs=
    # docker username
  - secure: FnOG55Iz1QlBmW2MEmHksNoHE2QBOIIIWvt8EIhtEMs7Tp1HbFDlXjJbPAXxFzgXHsCX4LwdAF8iOyY1goL0X01i7sT5/ihGpaUyuexItKjSAsHsW1hqYuHqHYrouxDDidpAz3zyd78iFZZjirbxv4SSmcIJ0u1KvmueqCRZr3goa14FjzphJI3WPataV0iUecA4N3q9QJ8hShQzL23zKhlhPwbeepqEeVcF+g1P1hCiaooLEp8+sES85HLp6tADMCpkvdrC6llJ14NktUMaxlJKAD4Crr5avISDPttXcAnDAUW49jJI2y8MeMJiYPzcSobZzxGmJrToLiZu9ykUSaUqaXLCHhPOx17NNyBl9eyW2/7oDFyT2789Eo0HnmAvOYqFMts+p7qHChEQZLlqsV1dlTINxXuSYyPR3+7Irv1zTu/T3Jpw5ShowXtLv0/xfWLS0v/ZNN6VAGk2Fq0rBnliqNitgjsCNKzxbodblgPMQINk+mEXr9jmrvWmamcbh1dgl7SvYP59hlgSdMJ+KNNpwYIg6EsoFyR2bZrI446DIR4Ro5efXcbAkcuUjN5NLMMQ9nhBpuaMsarburPgDy6czwdPTfVhy009vLSB20xRjF06USIube8eGf96LCa+XH1M9/zUgCEHdDACPIOGV/rfSDWMPaWTt5NWJt4Z25s=
    # docker password
  - secure: pMkjaKDMJX4Cjvxvk/4sqSbiT7UPi4p6g+GzniY/jQtEhC4kw5UDcUnT0cCUmk8TEvEdb0A1GlcsvftL2Q0pQTlKaMh1hIek5Q3qdWu04sOk9DBr66CK7oOsIVL8ndzGldjW4BA/B/bf+MdqFi7HsBlqeVjCgU/pUidwQTtYeamDWsx7TK5GbXxossCq9Dr3b3A8RFapboAZ/UJn9D8+QgjpXbmK5UEYpbKx1fg89A9HNmSU/qih7loF0yf0vQ0ypmdQAX9xc73P2q+M+zDC7AR1wk9ZYEzzE7psB3yY/YcLY7Sd0aBwP/J4FABLOOUmdHSgw4/V1+VF8038ryeHUDhYYectBui9uC2ww7E2O7bZZalKWRDXiYFLZYGOKW2rR56JZoOxzf66mJQnJDOmBV741gXEgFGhlfuf600S38sAd6v6kZkZy5YzIV5Cwad3CY5jxymbFLu5YjLLvXQciTqsd7++O7+efQBsad7+CY9rhvT1V07xqPh1Hk4NSmTWyE9v6k+uQ96UMn5I2dqY4wzvridkyEYlHWqr0XSrSb58cq6BkhKwMWVOwQbJ8u5sfYlsx7upySsy5uiVNmmiIZ9S0BaM4Xp/r+M5btkokq/jfLDdZ1kLZLMkoQfuihzYbc+rIXBKJjwvBR0kiVVPPZ5SHSZPqjiT7tDNGkcFllc=
