before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
before_script:
- echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_BUILD_STATUS_WEBHOOK_URL"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_BUILD_STATUS_WEBHOOK_URL"
notifications:
  email: false
language: bash
services:
- docker
jobs:
  include:
  - stage: build
    script: make build
  - stage: deploy_commit
    script: make deploy_commit
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy_latest
  on:
    branch: master
env:
  global:
  - secure: brQqIVLwC6uLl/9JhlVfpoVTeUl/a6IIDekvC+eA9LcPLXmITh1WIDfRdWNKUDpk1jJv+QWG09r9yZY+bZnXj4gtXdawuc/9DjJNfNODzPmjSf0giufpf5LcfeM4JdF8y+uoy+BU1JXaf/PyLiigtvpfX/Dobn3uZkiNtLCf9PPJ8j5ylNxsEICOJP+B6sMcbqf+3Wwv1Sn9p4Fow8ilyh2k4l8baORGVufWoXidHqt7rZ8NX8zcJdXknBt3iWn7zSasGkG5LibAhV2yA01hhYlPGyiyKr3UIUvvphZsZeabsOCNrif3F3+VhUMvnhoijo2Pwt5NQ9s6UNZfsvgw1StLOucJnvKZ9NVcMGWt2ew+kYLDck6X8pOgCW6ZndsSgZ7kIVW8jOPfFo9nMXGA7xdgP0gAqtsUz5XRytUSOETNlL7d38AEa0LnV8Brr6QrxJYXZ+WLcc6qGgzWN7war95q0rH4UUgjruXOjuXrHPyomjm4pnS28McmgCTWjkAZ1CvPAda2DEUhLlE5jpORnZVIUoDcpSQrbgPtZZoh82p1mFGZKUuXiFOiI0jwJwomid6/PNVAobeuVjatHaxeGgmw+4ziLjeB0hMoXzKSSCPZjt3NaVxHlu2csOJj4g4j1FfnRD2St2Bso3cxe3itiFTW4bTESsgJveQrySlLvZg=
  - secure: QgboY7t+g16GVWsWzTuxRScjRZrmAgoM/XXUnaNxUu5Fe+IAlQWfPwkkUR6wZTlmSS7q2kOg0Qxb0YxojicFC+vT6TpI4h+QJGq533gaVdyaStRnfMP0q6uZfuQw7BTl6cGL8rSNZGqLc2AWxtQFMXaf97YBUati4kPtC78zx9MIhl5acEwvr6Ps7Fi/RNOuj8/+8ezt/ZW4MCatnLiklGSnYDLkMl1EgK+wP3if8L+TIrX4dqwGqQEetpza4DQeUSWZahAfg7WdNVSHKNKfRFqEFwQcom49ucQLeKntjfyFSeSFkEEIBXRzPY5ezfqUjfQv3IwNHqiKxrWuAY7LUKrl8KNwsv+/BKxD6VBglABGnW54ONSZSa76GlNk3ckNgow3OHxpANO/UcK4Lgj+HemnNCTzz8pRD2QU+VOdKGLShH+5xn57pTgbNPKLhnLhuBr62TpsWeYSjcgPwbPgS4SYxFtxoXPLnRdS9YZvzh7d8rEsPICVQjAJG/9iNcka6lcUVACS371uoQq5bgNKZ/TeeCvYAkIhqxYnIGTBYPfi2dAPKss0XIQfIKI7kQIQXbmN295re7ma/X1dAE8rAJkBV+r955YMy4Ni2aegnzVzX9dH/ccflAgnZJcPQEB6Mw0F5tcGmbaMhM0piweSMVopbh/MkU7vIYU/oqnxHJI=
  - secure: X4+ZHfWqgSH+RWHlZTeidT12vtDdg0XxdqbpzaZwgNlw5MqEpiC5m57fLs3rgmE8SrxV1uVF7GYc64etqyknGwJCCTwE0JoaAQPgXwoaNqHHHX63zG7hCiEduHdEQEV4nIKDp81B+wOK3nhAsmDttCNTLnCDBoRlIfc3iXEHRMKqLYe8OvG7cBdOhXHxzbbfBfbKdP5a2GcuDa+xIFqKFXY7MgVh4utdxArDiDTLaz/xX/0hoGToZe+gBvd7JeaZuqnZZoSpI+19BuFzrKQWRkVZoxHFm/blFYY3mRjVCOxE/2VB/qFRXfl12BeaDz61IjRzoi10KKKHHIRPQrDhJ4u4N4CdVJ77eh2OdcHtw9+BP4/9+SLWXeYPWrliZXlsQDlLUoFqLbpx3BfruuANYYimtY3pGNhjNhsyBCEoyDE/iSZttnCQbzFONZ6Kb6V5vXDzNIuHQZlspwJwrbsPkqYOT82EoL4pOGBL1s2f/P3NjNnXcZX+cIN2Lyz3MDKRBak/3hHpFatfX95QA5IJla2xT0QNClzbbjVe8TiK8JEZY23OKI5fxAATWl6PAtuLCNhop4WzgopN8MUfsEEGg0NqqtwejA6dLj1fIrYVgUyOKZMq2bX9Y16eJlDNp2pPAVyxCmhLiKgojDTk6tgesNodNRSu1PRVI0Iq8YthnXY=
