before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_BUILD_STATUS_WEBHOOK_URL"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_BUILD_STATUS_WEBHOOK_URL"
notifications:
  email: false
language: bash
services:
- docker
jobs:
  include:
  - stage: build
    script: make build
  - stage: deploy_commit
    script: make deploy_commit
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy_latest
  on:
    branch: master
env:
  matrix:
  - secure: WPB7qXOj0qrCWE9vjFOx8WVjIamkV7uh4dxHBNjbfEhyuNsluA5AEfPpFGTh6jVu3Uz3RV1B8FkxF4wzwPiNcJgkST1LGJSgng9BbvpGIGldQ1Mri1hCUuXovgG7ZmcEXtoWmT7zT767JgVALdEQ6n/Wf0neLzvz7gD8hzkYvZRYeZjceHAIGFJBcxZcpBhYd9EAy4q7f3KEIeol+q+b8b7yq2njOM6UZSKW6TpbjD32i8aPR1rvntJt8B74DuIHDP2eNSMMii4DYuMwXZP0tbYDcRrhSQVBGBwEqc6pSa/qmN4LBPh4YpM/FmA0qKpQ3ibiAFb2DgIKOwTd4Hsfy+bFel6n6l1PExSMJb6yNUE1Ewtx954rWfv/LmTxfIJJ06KY8JwWKHifdYCgvByl1ALgTqn34RRWySUVdspH95NxPshkQyBKIxvGKu3a2ocl0i8iWsSFEtMn8fkNaQ7LJs0opu6vZSbCaiP+JnqG+tkbW7/Nc8J93S6xkiN+rRzDPRxpya8wdxH3076weAyFjFfJD13sLIPn0dzzBHyLY+Q6/5K/FwWFsKe6whr6Djr1I3ATvAV6SL+aUj4g2TSNDJWFVbK9STTglvCxyptVS7UwMyl4WKNqcBOK/6y0frTkBlWwOih0aowVKL0nZe881j7F8bPziGG6Z2BrPacpzRw=
  - secure: Kt+XMv3WCZLEqYxwhtLClYdN0SymubFXu6vgNF2Q0DR3X/i3Nm5nWUaJBSq/9+bdZtjoXy/evTVxhsz5sVSi6J82bLyP/u+JUw0WHWmBavfDrpza+CGsLl9dBzUw5cTjb6h06PtHN8EFUTgP+JF27KxhKqzs6joqjyN7U+ORqZsz4wY+St8ri2cBxsGT2lmj07xyKQoGwjtTNZzEHvpRvNFwz0EQCkffoQC2T9lGBNF8B39WSUIfbXJeTNg4hDzxySYwnfXvg2LD8KgcgwENrimSAu+sGSnk6CcbiGaYjOOK8ZVCh/U9aZOq+Kt1s2p8p7UgCT8dO3KjD/z/xLj8v+pp/70yCCJzvtzTyQ2wanVyd2FzpNSGLS27CKyE9EtudAU/OOjQGAh+KgJ5X0pi25nzIVi61ePXI9qVG7eI9RfeNsz9sPuXpk3k0dRqq1jtzZo3etyCymSWnDP6lSxmerG4KhXFWJAM7bo43tZrFfslOb/9JtlBkBk1OVEHu91LhTkSRKNSTMmwAyOoQ/tMKc19ew18siOpRtDLdP7q55fQTU6u39aneS13VHeXwyGQ1iYv/dw31XOWy24yuIb4LOffCyXLYM6h6B5WimLsbihsbzlS+jeKEvMFxgzX2goVEzXD7bp+309oR1kz09qsdVGbPfB4iabMpsHNfdhVfcs=
  - secure: pZferGGOGNsbTDZDMvdtFz4hjt7CuSal5uw3D4tp2uHbcNRXlfiHK3LzAD3qqSKaJCU0vVtcvCAsbsAyezDjVJOponrsKiXY2ZXF+COFK+JRFIMorpnph0zHyi/XWQWg6D2FzsXEqBsic6JFopmtHljPXwRExQUtcU/s9H4bTGhhi4wXRCN9XkXV83xtHPZOPdXSL7vfNnmKLHWTQYW96AD09iWntYj7/vHkNplPTXvUSi1OSdXpjfCeHagWSvRvyWs64dd3+K5SBgJpM2OFUvcZNz7S4sEjfz+coLcgsHlXgOL3Byev+x1facfhG146nDKgTwP1rhVIQ6XKrtQhoxmLshm4S0tHJwhmeMXB1W/cZTAcNEbFwgnIgVDNmII8orjIo0753Mmr2bOuyv7hdC/8daxgAqsbGJ4PSJLRuf2mniOcWJaCvm6tm6WYXNHBZxMGt69lT+t8NBXWR291SmXY3IITx0LYc4NZgc7drG6EO2+MkjjFMXQza+5QlUHq+nzLmSYVfg0rzDLtyvqtXggdT0WUQmL1tryhTkFaupCMt6dlXVWZ2wIQ3DhoubZIIQW9FPaHOhb8cm7uW8zdpJKfNYB8Nxmne3w9g0BykbCCRbeWyU2Ax/G7iHwqHnX9WoKOeHWYZ3Tf0VuHXZmayY9WyXfaSgISkykkOIWC49c=
